const baseURL="/api"

export default {
                  USERLOGIN:baseURL+"/userlogin",
                  MENULIST:baseURL+"/menulist",
                  MENUINFO:baseURL+"/menuinfo",
                  MENUEDIT:baseURL+"/menuedit",
                  MENUDELETE:baseURL+"/menudelete",
                  MENUDADD:baseURL+"/menuadd",
                  ROLEADD:baseURL+"/roleadd",
                  ROLELIST:baseURL+"/rolelist",
                  ROLEINFO:baseURL+"/roleinfo",
                  ROLEEDIT:baseURL+"/roleedit",
                  ROLEDELETE:baseURL+"/roledelete",
                  USERADD:baseURL+"/useradd",
                  USERCOUNT:baseURL+"/usercount",
                  USERLIST:baseURL+"/userlist",
                  USERINFO:baseURL+"/userinfo",
                  USEREDIT:baseURL+"/useredit",
                  USERDELETE:baseURL+"/userdelete",
                  USERLOGIN:baseURL+"/userlogin",
                  CATELIST:baseURL+"/catelist",
                  CATEINFO:baseURL+"/cateinfo",
                  CATEEDIT:baseURL+"/cateedit",
                  CATEDELETE:baseURL+"/catedelete",
                  CATEADD:baseURL+"/cateadd",
                  SPECSADD:baseURL+"/specsadd",
                  SPECSEDIT:baseURL+"/specsedit",
                  SPECSINFO:baseURL+"/specsinfo",
                  SPECSDELETE:baseURL+"/specsdelete",
                  SPECSLIST:baseURL+"/specslist",
                  SPECSCOUNT:baseURL+"/specscount",
                  GOODSLIST:baseURL+"/goodslist",
                  GOODSADD:baseURL+"/goodsadd",
                  GOODSCOUNT:baseURL+"/goodscount",
                  GOODSINFO:baseURL+"/goodsinfo",
                  GOODSEDIT:baseURL+"/goodsedit",
                  GOODSDELETE:baseURL+"/goodsdelete",
                  BANNERLIST:baseURL+"/bannerlist",
                  BANNEREDIT:baseURL+"/banneredit",
                  BANNERADD:baseURL+"/banneradd",
                  BANNERDELETE:baseURL+"/bannerdelete",
                  BANNERINFO:baseURL+"/bannerinfo",
                  MEMBERLIST:baseURL+"/memberlist",
                  MEMBEREDIT:baseURL+"/memberedit",
                  MEMBERINFO:baseURL+"/memberinfo",
                  SECKADD:baseURL+"/seckadd",
                  SECKLIST:baseURL+"/secklist",
                  SECKINFO:baseURL+"/seckinfo",
                  SECKEDIT:baseURL+"/seckedit",
                  SECKDELETE:baseURL+"/seckdelete",
                  

             
  
  
}